#include <stdio.h>
#include <stdlib.h>
#include <string.h>

//since returned value will be string of strings, char** is needed
char** split_string(char* input, const char delimit)
{
   //tokenized_string is the final output once the string has been split
   //tokens are the individual peices generated by the split function
    char** tokenized_string;

    //temporary pointer string to hold the passed input
    //this is necessary not to change the inputted string
    char* temp_string = input;

   //size_t is for size of object, it is used in this case to allocate memory
    size_t mem = 0;

    //temporary string to hold previous comma
    char* prev;

    //defining local delimiter variable 
    char delim[2];
    delim[0] = delimit;
    delim[1] = 0;

    //new tricky way I learned to loop through the string input
    while (*temp_string)
    {
	//if current character is equal to the delimiter, we have to split the cake 
        if (*temp_string == delimit)
        {
	    prev = temp_string;
            mem = mem + 1;
        }
	//have to increase count in order to evaluate next character
        temp_string = temp_string + 1;
    }
    //need to increase the memory count by
    mem += prev < (input + strlen(input) - 1);

    //allocating the necessary memory to tokenized_string 
    tokenized_string = malloc(sizeof(char*) * ++mem);

    if (tokenized_string)
    {
	//parses string with a delimiter strtok does this
        size_t idx  = 0;
        char* token = strtok(input, delim);

	//run through each token
        while (token)
        {
            *(tokenized_string + idx++) = strdup(token);
            token = strtok(0, delim);
        }
        *(tokenized_string + idx) = 0;
    }

    return tokenized_string;
}


int humidity_handler(char* hinput)
{
	//handles the humidity inputs, sets responses to different humidities
	int score;
	int numb;
	numb = atoi(hinput);;
	if (numb >= 85) {
		score = 3;
	}else if (numb >= 75) {
		score = 2;
	}else if (numb >= 65) {
		score = 1;
	}else{
		score = 0;
	}
	return score;
}

int tempH_handler(char* tinput)
{
	//handles high temperature, sets responses to different temperatures
	int score;
	int numb;
	numb = atoi(tinput);
	if (numb >= 85) {
		score = 3;
	}else if (numb >= 75) {
		score = 2;
	}else if (numb >= 65) {
		score = 1;
	}else {
		score = 0;
	}
	return score;
}

int tempL_handler(char* tinput)
{
	//handles low temperature, sets responses to different temperatures
        int score;
        int numb;
	numb = atoi(tinput);
        if(numb >= 77) {
                score = 3;
        }else if (numb >= 67) {
                score = 2;
        }else if (numb >= 57) {
                score = 1;
        }else {
                score = 0;
	}
        return score;
}


int precipitation_handler(char* pinput)
{
	//handles precipitation, sets responses to different precipitations
	int score;
	int numb;
	numb = atoi(pinput);
	if(numb >= 5) {
		score = 10;
	}else if (numb >= 4) {
		score = 8;
	}else if (numb >= 3) {
		score = 6;
	}else if (numb >= 2) {
		score = 4;
	}else if (numb >= 1) {
		score = 2;
	}else {
		score = 0;
	}
	return score;
}

int forcast_handler(char* finput)
{
	//handles forcast, sets responses to different forcasts
	int score = 0;
	if(strcmp("Partly Cloudy",finput)) {
		score = 1;
	}else if (strcmp("Cloudy",finput)) {
		score = 2;
	}else if (strcmp("Clear",finput)) {
		score = 0;
	}else {
		printf("Input incorrect");
	}
	return score;
}

int make_integer(char* input)
{
	//makes string values into integers
	int result;
	result = atoi(input);
	return result;
}

char* clothes_handler(int hum, int tempH, int tempL, int precip, int forcast)
{
	//handles responses to different values to humidity, temperature etc
	//prints the what you should wear for the day based on inputs
	int overall_score = 0;
	char* wear;
	if(hum >= 3) {
		overall_score += 2;
	}else if (hum >= 2) {
		overall_score += 1;
	}else {
		overall_score += 0;
	}
	if(tempH >= 3) {
                overall_score += 0;
        }else if (tempH >= 2) {
                overall_score += 1;
        }else {
                overall_score += 2;
        }
	if(tempL >= 3) {
                overall_score += 0;
        }else if (tempL >= 2) {
                overall_score += 1;
        }else {
                overall_score += 2;
        }
	if(precip >= 3) {
                overall_score += 2;
        }else if (precip >= 2) {
                overall_score += 1;
        }else {
                overall_score += 0;
        }
	if(forcast >= 3) {
                overall_score += 2;
        }else if (forcast >= 2) {
                overall_score += 1;
        }else {
                overall_score += 0;
        }
	printf("\nScore Final: %d\n",overall_score);
	printf("\nWhat should you wear:\n");
	//decision matrix
	if(overall_score >= 10) {
		printf("A jacket with pants and long sleeve shirt");
	}else if (overall_score >= 8) {
		printf("Pants and long sleeve shirt");
	}else if (overall_score >= 6) {
		printf("Pants and short sleeve shirt");
	}else if (overall_score >= 4) {
		printf("Shorts and a short sleeve shirt");
	}else {
		printf("Methinks it is hot, wear underwear");
	}
	printf("\n\n");
}


int main()
{
	//Taking the entire file and putting it into the array full_lines
	FILE * fPointer;
	fPointer = fopen("data.txt", "r");

	//setting up initial values for main
	int i = 0;
	const int number_of_days = 14;
	char** tokens;
	char full_lines[number_of_days][150];
	char Line[150];
	char dates[number_of_days][150];
	char humidity[number_of_days][150];
	char tempH[number_of_days][150];
	char tempL[number_of_days][150];
	char precipitation[number_of_days][150];
	char overall[number_of_days][150];

	//handles the amount of days, adds lines (i.e. days), to the 2d array
	while(i < number_of_days){
		fgets(Line, 150, fPointer);
		strcpy(full_lines[i], Line);
		i++;
	}
	//splits the 2d array into arrays that can be called by function(i.e. humidity)
	for(i=0; i<number_of_days; i++)
	{
	        tokens = split_string(full_lines[i], ',');

		strcpy(dates[i],tokens[0]);
		strcpy(humidity[i],tokens[1]);
		strcpy(tempH[i],tokens[2]);
		strcpy(tempL[i],tokens[3]);
		strcpy(precipitation[i],tokens[4]);
		strcpy(overall[i],tokens[5]);
	}
	//initializing scores and values to 0
	int phumidity = 0;
        int ptempH = 0;
        int ptempL = 0;
        int pprecipitation = 0;
        int forcast = 0;


	int phumidity_score = 0;
	int ptempH_score = 0;
	int ptempL_score = 0;
	int pprecipitation_score = 0;
	int forcast_score = 0;
	int total_score = 0;
	//increases score and current weather values by their necessary inputs
	for(i=1; i<number_of_days; i++)
	{
		phumidity += make_integer(humidity[i]);
                ptempH += make_integer(tempH[i]);
                ptempL += make_integer(tempL[i]);
                pprecipitation += make_integer(precipitation[i]);

		phumidity_score += humidity_handler(humidity[i]);
		ptempH_score += tempH_handler(tempH[i]);
		ptempL_score += tempL_handler(tempL[i]);
		pprecipitation_score += precipitation_handler(precipitation[i]);
		forcast_score += forcast_handler(overall[i]);
		total_score = phumidity + ptempH + ptempL + pprecipitation + forcast;

	}
	//divides the output by the number of days to get the average
	phumidity /= number_of_days -1;
	ptempH /= number_of_days - 1;
	ptempL /= number_of_days - 1;
	pprecipitation /= number_of_days - 1;
	//printing results to terminal
	printf("%d day projection:\n", number_of_days);
	printf("From: %s To: %s\n", dates[1], dates[number_of_days - 1]);
	printf("Humidity: %d\n",phumidity);
	printf("High Temperature: %d\n",ptempH);
	printf("Low Temperature: %d\n",ptempL);
	printf("Precipitation amount: 0.0%d\n",pprecipitation);

	printf("Humidity Score: %d\n",phumidity_score);
        printf("High Temperature Score: %d\n",ptempH_score);
        printf("Low Temperature Score: %d\n",ptempL_score);
        printf("Precipitation Score: %d\n",pprecipitation_score);
        printf("Forecast Score: %d\n",forcast_score);
	//what should you wear? Function handles this.
	clothes_handler(phumidity_score, ptempH_score, ptempL_score, pprecipitation_score, forcast_score);
	return 0;
}
